import {
  COOKIE_SESSION_KEY,
  OTP_VALIDITY_DURATION,
  RESEND_WAIT_DURATION,
  SESSION_EXPIRATION_SECONDS,
} from "./constants";

export {
  COOKIE_SESSION_KEY,
  OTP_VALIDITY_DURATION,
  RESEND_WAIT_DURATION,
  SESSION_EXPIRATION_SECONDS,
};
